apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: nginx-ingress-controller
spec:
  template:
    metadata:
      labels:
        name: nginx-ingress
    spec:
      nodeSelector:
        node-role.kubernetes.io/role: nginx-ingress
      hostNetwork: true
      serviceAccountName: ingress
      containers:
      - image: nginxdemos/nginx-ingress:0.8.1
        imagePullPolicy: Always
        name: nginx-ingress
        ports:
        - containerPort: 80
          hostPort: 80
        - containerPort: 443
          hostPort: 443
        # Uncomment the lines below to enable extensive logging and/or customization of
        # NGINX configuration with configmaps     自定义nginx，默认没开启
        args:
         - -v=3
         - -nginx-configmaps=default/nginx-config

